namespace Hifz.Models;

/// <summary>
/// Represents the Surahs of the Quran.
/// </summary>
/// <remarks>
/// This enum is currently empty and can be populated with Surah names and numbers as needed.
/// </remarks>


public enum Surah
{
    Al_Fatiha = 1,
    Al_Baqara = 2,
    Aal_Imran = 3,
    An_Nisa = 4,
    Al_Maida = 5,
    Al_Anam = 6,
    Al_Araf = 7,
    Al_Anfal = 8,
    At_Tawba = 9,
    Yunus = 10,
    Hud = 11,
    Yusuf = 12,
    Ar_Rad = 13,
    Ibrahim = 14,
    Al_Hijr = 15,
    An_Nahl = 16,
    Al_Isra = 17,
    Al_Kahf = 18,
    Maryam = 19,
    Ta_Ha = 20,
    Al_Anbiya = 21,
    Al_Hajj = 22,
    Al_Muminun = 23,
    An_Nur = 24,
    Al_Furqan = 25,
    Ash_Shuara = 26,
    An_Naml = 27,
    Al_Qasas = 28,
    Al_Ankabut = 29,
    Ar_Rum = 30,
    Luqman = 31,
    As_Sajda = 32,
    Al_Ahzab = 33,
    Saba = 34,
    Fatir = 35,
    Ya_Sin = 36,
    As_Saffat = 37,
    Sad = 38,
    Az_Zumar = 39,
    Ghafir = 40,
    Fussilat = 41,
    Ash_Shura = 42,
    Az_Zukhruf = 43,
    Ad_Dukhan = 44,
    Al_Jathiya = 45,
    Al_Ahqaf = 46,
    Muhammad = 47,
    Al_Fath = 48,
    Al_Hujurat = 49,
    Qaf = 50,
    Adh_Dhariyat = 51,
    At_Tur = 52,
    An_Najm = 53,
    Al_Qamar = 54,
    Ar_Rahman = 55,
    Al_Waqia = 56,
    Al_Hadid = 57,
    Al_Mujadila = 58,
    Al_Hashr = 59,
    Al_Mumtahina = 60,
    As_Saff = 61,
    Al_Jumuah = 62,
    Al_Munafiqun = 63,
    At_Taghabun = 64,
    At_Talaq = 65,
    At_Tahrim = 66,
    Al_Mulk = 67,
    Al_Qalam = 68,
    Al_Haqqa = 69,
    Al_Maarij = 70,
    Nuh = 71,
    Al_Jinn = 72,
    Al_Muzzammil = 73,
    Al_Muddathir = 74,
    Al_Qiyama = 75,
    Al_Insan = 76,
    Al_Mursalat = 77,
    An_Naba = 78,
    An_Naziat = 79,
    Abasa = 80,
    At_Takwir = 81,
    Al_Infitar = 82,
    Al_Mutaffifin = 83,
    Al_Inshiqaq = 84,
    Al_Buruj = 85,
    At_Tariq = 86,
    Al_Ala = 87,
    Al_Ghashiya = 88,
    Al_Fajr = 89,
    Al_Balad = 90,
    Ash_Shams = 91,
    Al_Lail = 92,
    Ad_Duhaa = 93,
    Ash_Sharh = 94,
    At_Tin = 95,
    Al_Alaq = 96,
    Al_Qadr = 97,
    Al_Bayyina = 98,
    Az_Zalzala = 99,
    Al_Adiyat = 100,
    Al_Qaria = 101,
    At_Takathur = 102,
    Al_Asr = 103,
    Al_Humazah = 104,
    Al_Fil = 105,
    Quraish = 106,
    Al_Maun = 107,
    Al_Kawthar = 108,
    Al_Kafirun = 109,
    An_Nasr = 110,
    Al_Masad = 111,
    Al_Ikhlas = 112,
    Al_Falaq = 113,
    An_Nas = 114,
}
