using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Hifz.Models;
using Hifz.Models.enums;

namespace Hifz.Common.Helper
{
    public static class Formatting
    {
        private static readonly Dictionary<Surah, string> ArabicSurahNames =
            new()
            {
                { Surah.Al_Fatiha, "الفاتحة" },
                { Surah.Al_Baqara, "البقرة" },
                { Surah.Aal_Imran, "آل عمران" },
                { Surah.An_Nisa, "النساء" },
                { Surah.Al_Maida, "المائدة" },
                { Surah.Al_Anam, "الأنعام" },
                { Surah.Al_Araf, "الأعراف" },
                { Surah.Al_Anfal, "الأنفال" },
                { Surah.At_Tawba, "التوبة" },
                { Surah.Yunus, "يونس" },
                { Surah.Hud, "هود" },
                { Surah.Yusuf, "يوسف" },
                { Surah.Ar_Rad, "الرعد" },
                { Surah.Ibrahim, "إبراهيم" },
                { Surah.Al_Hijr, "الحجر" },
                { Surah.An_Nahl, "النحل" },
                { Surah.Al_Isra, "الإسراء" },
                { Surah.Al_Kahf, "الكهف" },
                { Surah.Maryam, "مريم" },
                { Surah.Ta_Ha, "طه" },
                { Surah.Al_Anbiya, "الأنبياء" },
                { Surah.Al_Hajj, "الحج" },
                { Surah.Al_Muminun, "المؤمنون" },
                { Surah.An_Nur, "النور" },
                { Surah.Al_Furqan, "الفرقان" },
                { Surah.Ash_Shuara, "الشعراء" },
                { Surah.An_Naml, "النمل" },
                { Surah.Al_Qasas, "القصص" },
                { Surah.Al_Ankabut, "العنكبوت" },
                { Surah.Ar_Rum, "الروم" },
                { Surah.Luqman, "لقمان" },
                { Surah.As_Sajda, "السجدة" },
                { Surah.Al_Ahzab, "الأحزاب" },
                { Surah.Saba, "سبأ" },
                { Surah.Fatir, "فاطر" },
                { Surah.Ya_Sin, "يس" },
                { Surah.As_Saffat, "الصافات" },
                { Surah.Sad, "ص" },
                { Surah.Az_Zumar, "الزمر" },
                { Surah.Ghafir, "غافر" },
                { Surah.Fussilat, "فصلت" },
                { Surah.Ash_Shura, "الشورى" },
                { Surah.Az_Zukhruf, "الزخرف" },
                { Surah.Ad_Dukhan, "الدخان" },
                { Surah.Al_Jathiya, "الجاثية" },
                { Surah.Al_Ahqaf, "الأحقاف" },
                { Surah.Muhammad, "محمد" },
                { Surah.Al_Fath, "الفتح" },
                { Surah.Al_Hujurat, "الحجرات" },
                { Surah.Qaf, "ق" },
                { Surah.Adh_Dhariyat, "الذاريات" },
                { Surah.At_Tur, "الطور" },
                { Surah.An_Najm, "النجم" },
                { Surah.Al_Qamar, "القمر" },
                { Surah.Ar_Rahman, "الرحمن" },
                { Surah.Al_Waqia, "الواقعة" },
                { Surah.Al_Hadid, "الحديد" },
                { Surah.Al_Mujadila, "المجادلة" },
                { Surah.Al_Hashr, "الحشر" },
                { Surah.Al_Mumtahina, "الممتحنة" },
                { Surah.As_Saff, "الصف" },
                { Surah.Al_Jumuah, "الجمعة" },
                { Surah.Al_Munafiqun, "المنافقون" },
                { Surah.At_Taghabun, "التغابن" },
                { Surah.At_Talaq, "الطلاق" },
                { Surah.At_Tahrim, "التحريم" },
                { Surah.Al_Mulk, "الملك" },
                { Surah.Al_Qalam, "القلم" },
                { Surah.Al_Haqqa, "الحاقة" },
                { Surah.Al_Maarij, "المعارج" },
                { Surah.Nuh, "نوح" },
                { Surah.Al_Jinn, "الجن" },
                { Surah.Al_Muzzammil, "المزمل" },
                { Surah.Al_Muddathir, "المدثر" },
                { Surah.Al_Qiyama, "القيامة" },
                { Surah.Al_Insan, "الإنسان" },
                { Surah.Al_Mursalat, "المرسلات" },
                { Surah.An_Naba, "النبأ" },
                { Surah.An_Naziat, "النازعات" },
                { Surah.Abasa, "عبس" },
                { Surah.At_Takwir, "التكوير" },
                { Surah.Al_Infitar, "الانفطار" },
                { Surah.Al_Mutaffifin, "المطففين" },
                { Surah.Al_Inshiqaq, "الانشقاق" },
                { Surah.Al_Buruj, "البروج" },
                { Surah.At_Tariq, "الطارق" },
                { Surah.Al_Ala, "الأعلى" },
                { Surah.Al_Ghashiya, "الغاشية" },
                { Surah.Al_Fajr, "الفجر" },
                { Surah.Al_Balad, "البلد" },
                { Surah.Ash_Shams, "الشمس" },
                { Surah.Al_Lail, "الليل" },
                { Surah.Ad_Duhaa, "الضحى" },
                { Surah.Ash_Sharh, "الشرح" },
                { Surah.At_Tin, "التين" },
                { Surah.Al_Alaq, "العلق" },
                { Surah.Al_Qadr, "القدر" },
                { Surah.Al_Bayyina, "البينة" },
                { Surah.Az_Zalzala, "الزلزلة" },
                { Surah.Al_Adiyat, "العاديات" },
                { Surah.Al_Qaria, "القارعة" },
                { Surah.At_Takathur, "التكاثر" },
                { Surah.Al_Asr, "العصر" },
                { Surah.Al_Humazah, "الهمزة" },
                { Surah.Al_Fil, "الفيل" },
                { Surah.Quraish, "قريش" },
                { Surah.Al_Maun, "الماعون" },
                { Surah.Al_Kawthar, "الكوثر" },
                { Surah.Al_Kafirun, "الكافرون" },
                { Surah.An_Nasr, "النصر" },
                { Surah.Al_Masad, "المسد" },
                { Surah.Al_Ikhlas, "الإخلاص" },
                { Surah.Al_Falaq, "الفلق" },
                { Surah.An_Nas, "الناس" },
            };

        private static readonly Dictionary<Surah, string> EnglishSurahNames =
            new()
            {
                { Surah.Al_Fatiha, "Al-Fatiha" },
                { Surah.Al_Baqara, "Al-Baqarah" },
                { Surah.Aal_Imran, "Ali 'Imran" },
                { Surah.An_Nisa, "An-Nisa" },
                { Surah.Al_Maida, "Al-Ma'idah" },
                { Surah.Al_Anam, "Al-An'am" },
                { Surah.Al_Araf, "Al-A'raf" },
                { Surah.Al_Anfal, "Al-Anfal" },
                { Surah.At_Tawba, "At-Tawbah" },
                { Surah.Yunus, "Yunus" },
                { Surah.Hud, "Hud" },
                { Surah.Yusuf, "Yusuf" },
                { Surah.Ar_Rad, "Ar-Ra'd" },
                { Surah.Ibrahim, "Ibrahim" },
                { Surah.Al_Hijr, "Al-Hijr" },
                { Surah.An_Nahl, "An-Nahl" },
                { Surah.Al_Isra, "Al-Isra" },
                { Surah.Al_Kahf, "Al-Kahf" },
                { Surah.Maryam, "Maryam" },
                { Surah.Ta_Ha, "Ta-Ha" },
                { Surah.Al_Anbiya, "Al-Anbiya" },
                { Surah.Al_Hajj, "Al-Hajj" },
                { Surah.Al_Muminun, "Al-Mu'minun" },
                { Surah.An_Nur, "An-Nur" },
                { Surah.Al_Furqan, "Al-Furqan" },
                { Surah.Ash_Shuara, "Ash-Shu'ara" },
                { Surah.An_Naml, "An-Naml" },
                { Surah.Al_Qasas, "Al-Qasas" },
                { Surah.Al_Ankabut, "Al-Ankabut" },
                { Surah.Ar_Rum, "Ar-Rum" },
                { Surah.Luqman, "Luqman" },
                { Surah.As_Sajda, "As-Sajdah" },
                { Surah.Al_Ahzab, "Al-Ahzab" },
                { Surah.Saba, "Saba" },
                { Surah.Fatir, "Fatir" },
                { Surah.Ya_Sin, "Ya-Sin" },
                { Surah.As_Saffat, "As-Saffat" },
                { Surah.Sad, "Sad" },
                { Surah.Az_Zumar, "Az-Zumar" },
                { Surah.Ghafir, "Ghafir" },
                { Surah.Fussilat, "Fussilat" },
                { Surah.Ash_Shura, "Ash-Shura" },
                { Surah.Az_Zukhruf, "Az-Zukhruf" },
                { Surah.Ad_Dukhan, "Ad-Dukhan" },
                { Surah.Al_Jathiya, "Al-Jathiyah" },
                { Surah.Al_Ahqaf, "Al-Ahqaf" },
                { Surah.Muhammad, "Muhammad" },
                { Surah.Al_Fath, "Al-Fath" },
                { Surah.Al_Hujurat, "Al-Hujurat" },
                { Surah.Qaf, "Qaf" },
                { Surah.Adh_Dhariyat, "Adh-Dhariyat" },
                { Surah.At_Tur, "At-Tur" },
                { Surah.An_Najm, "An-Najm" },
                { Surah.Al_Qamar, "Al-Qamar" },
                { Surah.Ar_Rahman, "Ar-Rahman" },
                { Surah.Al_Waqia, "Al-Waqi'ah" },
                { Surah.Al_Hadid, "Al-Hadid" },
                { Surah.Al_Mujadila, "Al-Mujadilah" },
                { Surah.Al_Hashr, "Al-Hashr" },
                { Surah.Al_Mumtahina, "Al-Mumtahanah" },
                { Surah.As_Saff, "As-Saf" },
                { Surah.Al_Jumuah, "Al-Jumu'ah" },
                { Surah.Al_Munafiqun, "Al-Munafiqun" },
                { Surah.At_Taghabun, "At-Taghabun" },
                { Surah.At_Talaq, "At-Talaq" },
                { Surah.At_Tahrim, "At-Tahrim" },
                { Surah.Al_Mulk, "Al-Mulk" },
                { Surah.Al_Qalam, "Al-Qalam" },
                { Surah.Al_Haqqa, "Al-Haqqah" },
                { Surah.Al_Maarij, "Al-Ma'arij" },
                { Surah.Nuh, "Nuh" },
                { Surah.Al_Jinn, "Al-Jinn" },
                { Surah.Al_Muzzammil, "Al-Muzzammil" },
                { Surah.Al_Muddathir, "Al-Muddaththir" },
                { Surah.Al_Qiyama, "Al-Qiyamah" },
                { Surah.Al_Insan, "Al-Insan" },
                { Surah.Al_Mursalat, "Al-Mursalat" },
                { Surah.An_Naba, "An-Naba" },
                { Surah.An_Naziat, "An-Nazi'at" },
                { Surah.Abasa, "Abasa" },
                { Surah.At_Takwir, "At-Takwir" },
                { Surah.Al_Infitar, "Al-Infitar" },
                { Surah.Al_Mutaffifin, "Al-Mutaffifin" },
                { Surah.Al_Inshiqaq, "Al-Inshiqaq" },
                { Surah.Al_Buruj, "Al-Buruj" },
                { Surah.At_Tariq, "At-Tariq" },
                { Surah.Al_Ala, "Al-A'la" },
                { Surah.Al_Ghashiya, "Al-Ghashiyah" },
                { Surah.Al_Fajr, "Al-Fajr" },
                { Surah.Al_Balad, "Al-Balad" },
                { Surah.Ash_Shams, "Ash-Shams" },
                { Surah.Al_Lail, "Al-Layl" },
                { Surah.Ad_Duhaa, "Ad-Duhaa" },
                { Surah.Ash_Sharh, "Ash-Sharh" },
                { Surah.At_Tin, "At-Tin" },
                { Surah.Al_Alaq, "Al-Alaq" },
                { Surah.Al_Qadr, "Al-Qadr" },
                { Surah.Al_Bayyina, "Al-Bayyinah" },
                { Surah.Az_Zalzala, "Az-Zalzalah" },
                { Surah.Al_Adiyat, "Al-Adiyat" },
                { Surah.Al_Qaria, "Al-Qari'ah" },
                { Surah.At_Takathur, "At-Takathur" },
                { Surah.Al_Asr, "Al-Asr" },
                { Surah.Al_Humazah, "Al-Humazah" },
                { Surah.Al_Fil, "Al-Fil" },
                { Surah.Quraish, "Quraysh" },
                { Surah.Al_Maun, "Al-Ma'un" },
                { Surah.Al_Kawthar, "Al-Kawthar" },
                { Surah.Al_Kafirun, "Al-Kafirun" },
                { Surah.An_Nasr, "An-Nasr" },
                { Surah.Al_Masad, "Al-Masad" },
                { Surah.Al_Ikhlas, "Al-Ikhlas" },
                { Surah.Al_Falaq, "Al-Falaq" },
                { Surah.An_Nas, "An-Nas" },
            };

        public static string GetLocalizedSurahName(Surah surah)
        {
            var isArabic = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "ar";
            var dict = isArabic ? ArabicSurahNames : EnglishSurahNames;
            return dict.TryGetValue(surah, out var name) ? name : surah.ToString();
        }

        public static string GetLocalizedDayName(ClassDaysEnum day)
        {
            var currentLanguage = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            if (currentLanguage == "ar")
            {
                return day switch
                {
                    ClassDaysEnum.sunday => "الأحد",
                    ClassDaysEnum.monday => "الإثنين",
                    ClassDaysEnum.tuesday => "الثلاثاء",
                    ClassDaysEnum.wednesday => "الأربعاء",
                    ClassDaysEnum.thursday => "الخميس",
                    ClassDaysEnum.friday => "الجمعة",
                    ClassDaysEnum.saturday => "السبت",
                    _ => day.ToString(),
                };
            }

            // English translations (default)
            return day switch
            {
                ClassDaysEnum.sunday => "Sunday",
                ClassDaysEnum.monday => "Monday",
                ClassDaysEnum.tuesday => "Tuesday",
                ClassDaysEnum.wednesday => "Wednesday",
                ClassDaysEnum.thursday => "Thursday",
                ClassDaysEnum.friday => "Friday",
                ClassDaysEnum.saturday => "Saturday",
                _ => day.ToString(),
            };
        }
    }
}
